.github/CODEOWNERS
The CODEOWNERS file is presently valid but isn't automatically requesting reviews from the codeowners group. AFAIK this should solve it, I hope
=> Modify CODEOWNERS file

openstates/scrape/base.py
This PR adds in a small fix to the Kafka Producer instantiation.  Specifically, we are using the `JSONEncoder` function to transform `datetime` values into strings.  We do this because we are unable to send `datetime` values to Kafka clusters.
=> Kafka datetime encoding

openstates/scrape/jurisdiction.py, pyproject.toml
This change looks to re-implement `legislative_sessions` as a property (as opposed to a manually defined list), and retire the legacy `legislative_sessions` as `historical_legislative_sessions`. We include the ability to `opt_for_new` to give us flexibility when re-writing sessions, custom backfill and more. This is particularly relevant when additions are made to the main openstates core and scrapers that include new session information.
=> legislative_sessions update

.github/workflows/build-scrapers.yml
In this P.R, we're adding a workflow to this repository to trigger the CI of the cyclades-scrapers.
The cyclades-scrapers CI will build a new docker image, which will download and install the most recent version of this repository. This allows us to see changes made to the core immediately reflected. Currently, we only see changes made here reflected when separate changes are made at the scraper level.
=> DAT-432: Trigger cyclades-scraper rebuild whenever there's changes to this repo.

pyproject.toml
In this P.R, we make changes to the pyproject.toml to allow us to install the cyclades-core as 'cyclades' as opposed to 'openstates'. This will require a conjunctive change at the scrapers level. This was inspired by [apache-airflow
](https://github.com/apache/airflow), which is installed as 'apache-airflow' but imported as 'airflow' taking advantage of the naming convention of the directory (we too have the directory named openstates instead of cyclades)
Note that while the package is _installed_ as cyclades, it will still be imported as openstates. That is, we would use
`pip install cyclades`
`poetry add cyclades`
but at the python level, we'd continue to use `from openstates import ...`
This allows us to have our own version (I suggest beginning from 1.0) and implementing version bumps …
=> Change package installation name

openstates/scrape/base.py
This PR updates the `save_object` function to process and send vote events to the Kafka cluster. Previously, vote events were not being routed to Kafka due to missing logic in the conditional checks. This change introduces proper handling for vote events alongside bills and ancillary JSONs. The changes have been thoroughly tested locally and with full DAG runs.
**Changes Made:**
- Added a conditional block to detect and process vote events (`if hasattr(obj, 'motion_text')`).
- Logs vote events using the bill identifier and routes them to Kafka for further processing.
=> Adding Conditional for Vote Events in Cache Block

openstates/cli/update.py, openstates/scrape/jurisdiction.py
Whenever our scrapers fire up, they compile the legislative sessions hard coded in the scrapers, and combine them with those found in Cronos. We want to be able to write sessions for all jurisdictions to cronos so that we can query all sessions from cronos. To do this, we will:
- Add a method to the `Jurisdiction` class to create a new session in cronos
- Call this method once in the `check_session_list` function in `update.py`
It was considered to handle this solely in the jurisdiction class when the `legislative_sessions` property is called. However, the 'legislative_sessions' is a property called a few times in a scrape, and we want to reduce the load on cronos and the database. `check_session_list` is called once per scrape, and is most appropriate from which to call the new method.
=> DAT-496 updated core to write new sessions to cronos

openstates/scrape/jurisdiction.py
In this P.R, we make a simple, 1 line change to ensure that calling `new_sessions` (which overwrites `historical_legislative_sessions`) includes the [_scraped_name field now returned by cronos](https://github.com/washabstract/cronos/pull/33)
=> serialized the scraped_name field from cronos

openstates/cli/update.py, openstates/scrape/base.py, openstates/scrape/jurisdiction.py, openstates/settings.py
In this P.R, we:
- Undo the previous cacheing, which checked the cyclades S3 bucket directly to see if a bill exists before continuing to dump. This not only was ineffective at reducing scrape time, but prevents us from writing vote events or any document past the first into S3
- Implement a download and write to an S3 cacheing bucket at the start and end of a scrape. 
- Note that the nature of openstates scrapers is to dump all HTMLs to a single bucket. While small, this will develop bloat over time as we continue to sync all the scrapes. In the future, we'll want to see if we can stratify by jurisdiction and eventually session to reduce the amount being copied into the image.
Each scraper is spun up in a pod, with no cache directory implemented yet. By default, openstates creates a …
=> DAT-509: Fix Cacheing for OS

openstates/cli/update.py, openstates/scrape/base.py, openstates/scrape/jurisdiction.py
Here, we're fixing our cache process and the issue we had with legislative session syncing with cronos. Now, we
- Sync sessions to cronos first before resolving `self.legislative_sessions`
- Adjusted our cache'ing protocol to use the AWS CLI for download as opposed to boto3 client (we already were using it to upload updated cache)
- We update our cache to be stratified by jurisdiction name in the cache bucket, to reduce our read cost from S3 (and reduce scrape time becuase we're not downloading everything!)
=> Legislative session fix

openstates/cli/update.py, openstates/scrape/jurisdiction.py, openstates/scrape/schemas/jurisdiction.py
in this P.R, we're introducing a new arg to core for backfilling different sessions for a state.
We can use the `--backfill` flag followed by any amount of sessions in order to backfill a scrape for any given state (that's not CA).
This can be used with airflow where we can backfill for a single state with a single run using the `--backfill` args in the config.
=> --backfill in openstates

openstates/scrape/jurisdiction.py
Ugh forgot to add and commit this when making the initial P.R
Default arg for backfill to be none; this way, the standard scrape doesn't freak out when there's no backfill value
=> backfill default args

openstates/cli/update.py, openstates/scrape/base.py
This PR adds logic to the `save_object` method that prevents saving bill JSONs if a bill has not changed from what's already stored in S3. This logic is only enabled when running scrapers in fastmode (`--fastmode`).
**What's new:**
- If fastmode is enabled, and we confirm this scraped object is a bill, the scraper checks S3 (via `S3_BILLS_BUCKET`) for the current bill path.
- If the bill exists, we:
- Load both the existing and newly scraped bill JSONs.
- Strip the `_id` field from both (since it's regenerated with each run).
- Compare the remaining structure.
- If they match, we skip saving and log that the bill was unchanged.
- If the bill is not found in S3, or if there's any error during retrieval, we proceed with saving as usual.
**Why this matters:**
- Reduces unnecessary writes to …
=> Cache Block for Fastmode Argument

.github/workflows/update-scrapers.yml
In this P.R, we're introducing a workflow inspired by the scrapers repo's workflow that opens a PR in artemis on push.
This workflow
- checks out the scrapers branch
- updates poetry dependencies
- checks out a branch
- makes a PR
=> artemis inspired workflow to PR to scrapers

openstates/scrape/base.py
This PR updates our cache comparison logic to normalize date formats when comparing bill JSONs.
Michigan bill JSONs produce dates in a different format than what we store in S3, causing false mismatches and preventing the cache from functioning correctly.
We now serialize both the existing and new JSONs using `utils.JSONEncoderPlus` before comparison to ensure all dates are formatted consistently. 
This was tested locally on the Michigan scraper and worked as expected.
=> Revising Cache Logic to Account for Varied Date Formats

openstates/scrape/base.py
This PR updates the Kafka publishing logic to ensure that the jurisdiction string used as the topic name is always uppercase.
Currently, in the fastmode cache comparison block, the jurisdiction is converted to uppercase when building S3 paths (e.g., MI/2025-2026/HB 4001/...). However, when sending messages to Kafka, the jurisdiction was being passed as-is, which led to inconsistencies in topic naming (e.g., CA vs ca).
To enforce consistency across our pipeline and prevent issues related to mismatched topic names or consumers missing messages, we now normalize the Kafka topic to uppercase.
=> Ensuring Topics Are Always Uppercase

openstates/scrape/jurisdiction.py
- Avoid key error for unupdated cronos map
- Return the session details from create_session_in_cronos to avoid making multiple queries to cronos
=> BUG: new cronos sessions not updating in map

openstates/scrape/base.py
**Summary**
This PR updates `base.py` to remove the recently added `scraped_at` and `jurisdiction` fields from each bill JSON before caching or sending to Kafka.
**Problem**
The upstream OpenStates-Core schema introduced two new keys:
`scraped_at`: A volatile timestamp that changes on every scrape, breaking our cache logic. We already track relevant timestamps via `updated_at` in Elasticsearch.
`jurisdiction`: A redundant metadata field that duplicates information we manage separately (e.g., state ID and name).
**Fix**
We now drop these two fields before performing cache comparisons and before publishing to Kafka.
**Testing**
Tested successfully across multiple scrapes with consistent caching.
=> Remove Unnecessary Bill Data Affecting our Cache System

openstates/cli/update.py, openstates/scrape/base.py
In this P.R, we adjust our handling of arguments and env vars to separate the ability to enable OS cache'ing (through S3) and the ability to activate caching with using es cache
- `fastmode` will choose whether or not we use elastic for cache checking bills
- the `SYNC_S3_ARCHIVE` field will dictate whether or not we sync the remote S3 cache to the local _cache directory
- the 'ARCHIVE_CACHE_TO_S3' field will dictate whether or not we update the remote cache
=> Fix cache dir sync

openstates/scrape/base.py
Added date formatting for datetime.date objects in the `replace_none_in_dict` function.
Added a new condition in the `replace_none_in_dict` function to handle `datetime.date` objects by converting them to ISO format strings (`YYYY-MM-DD`). This ensures that date objects are properly serialized when processing bill data.
1. Create a dictionary containing a `datetime.date` object
2. Pass it through the `replace_none_in_dict` function
3. Verify that the date is converted to a string in the format 'YYYY-MM-DD'
When serializing bill data that contains date objects, these objects need to be converted to strings in a consistent format. Without this change, attempting to serialize a dictionary containing date objects would likely result in errors. This fix ensures proper JSON serialization of …
=> datetime flattening in json/dictionary flattening
